version: '3.8'

services:
  prod-db:
    image: postgres:14
    container_name: sync-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prod_db
    ports:
      - "5456:5432"

  dev-db:
    image: postgres:14
    container_name: sync-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    ports:
      - "5457:5432"

volumes:
  prod_data:
  dev_data:
